# -*- mode: python ; coding: utf-8 -*-

import os
import sys

# -----------------------------------------------------------------------------
# PyInstaller Spec File for Bili-Spotilive (One-File Executable)
#
# This file is automatically generated by the Gemini CLI.
# It is configured to bundle the application into a single executable.
# -----------------------------------------------------------------------------

block_cipher = None

# --- Data files ---
# We need to include all static assets (for the web UI) and the configuration file.
# The format is a list of tuples: ('source_path_on_disk', 'destination_path_in_exe')
datas = [
    ('static', 'static'),       # Bundle the entire 'static' directory
    ('config.json', '.')        # Bundle the main config file
]

# --- Analysis Section ---
# This is the main configuration block for the analysis phase.
a = Analysis(
    ['main.py'],  # The main entry point of the application
    pathex=[],    # No extra paths needed if run from the project root
    binaries=[],
    datas=datas,
    hiddenimports=[
        # --- Threading & Async ---
        'threading',
        # Flask-SocketIO relies on an async driver. 'threading' is a safe default
        # when not using eventlet or gevent.
        'engineio.async_drivers.threading',
        'engineio.async_drivers.eventlet',

        # --- BLiveDM ---
        # PyInstaller might miss these dynamically loaded or less obvious imports
        # from the blivedm library.
        'blivedm.handlers',
        'blivedm.clients.ws_base',
        'blivedm.clients.web',
        'blivedm.models.web',
        'blivedm.models.pb',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)

# --- PYZ (Python Zipped Archive) ---
# This bundles all the pure Python modules.
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# --- EXE (One-File Executable) ---
# This builds the single-file executable by combining the script, modules,
# and all data files into one file.
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Bili-Spotilive',  # Name of the final executable
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    runtime_tmpdir=None,  # Extracts to a temporary folder
    console=True,         # Show the console window for logs
    icon=None,            # You can specify an 'icon.ico' file here
)